POST http://localhost:5000/api/users
Content-Type: application/json

// username already exists, should return "username is taken"

{
  "username": "TestAcc",
  "email": "testemail@gmail.com",
  "password": "helloworld"
}